version: 2.1

workflows:
  build_and_publish:
    jobs:
      - build_resume
      - publish_resume:
          requires:
            - build_resume
          filters:
            branches:
              only: master

jobs:
  build_resume:
    docker:
      - image: marpteam/marp-cli:v0.21.0
        entrypoint: sh
    steps:
      - checkout
      - run:
          name: Build resume
          command: |
            # Interpolate env variables into Markdown
            yarn build:resume RESUME.md /tmp/resume.md
            # Markdown to PDF
            node ../.cli/marp-cli.js /tmp/resume.md -o /tmp/resume.pdf
      - save_cache:
          key: v1-resume-{{ .Revision }}
          paths:
            - /tmp/resume.pdf
  publish_resume:
    docker:
      - image: alpine
    steps:
      - restore_cache:
          key: v1-resume-{{ .Revision }}
      - run:
          name: Install AWS CLI
          command: apk update && apk add aws-cli
      - run:
          name: Publish resume
          command: aws s3 cp --acl public-read /tmp/resume.pdf s3://$S3_BUCKET/Resume.pdf
